[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "maki"
version = "2.0.0"
description = "Metagenomics using an Annotated K-mer Index"
authors = [{name="Sean Solari"}]

[tool.scikit-build]
wheel.packages = ["python/maki"]
cmake.build-type = "Release"
logging.level = "INFO"

[project.scripts]
maki = "maki.cli:main"
"maki.atb" = "maki.atb.cli:main"
