
add_subdirectory ("core")
add_subdirectory ("build")
add_subdirectory ("classify")

list (APPEND MAKI_BUILD_SOURCES ${MAKI_CORE_SOURCES})
set (MAKI_BUILD_SOURCES ${MAKI_BUILD_SOURCES} PARENT_SCOPE)

list (APPEND MAKI_CLASSIFY_SOURCES ${MAKI_BUILD_SOURCES})
set (MAKI_CLASSIFY_SOURCES ${MAKI_CLASSIFY_SOURCES} PARENT_SCOPE)
